namePrefix: staging-
nameSuffix: -v1
commonLabels:
  variant: staging
  org: acmeCorporation
commonAnnotations:
  note: Hello I am new staging!
bases:
  - ../../base
patchesStrategicMerge:
  - map.yaml
