apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- service.yaml
- deployment.yaml
namePrefix: prod-
commonLabels:
  app: prod
patchesStrategicMerge:
  - persistent-disk.yaml
