apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      volumes:
        - name: mysql-persistent-storage
          emptyDir: null
          gcePersistentDisk:
            pdName: mysql-persistent-storage
